### ISSUE TITLE
add triggers

### ISSUE THREAD

**Issue by smgd** [smgd/disco#2]
add triggers which will capture events on the desktop

for example: listen to desktop notifications and run this thing when desired notification is triggered

**Comment by madbird1304** [comment]
Done https://github.com/smgd/disco/commit/801e310082c7db5ac5dd081d1438c5d47fcf920d
To trigger diskach, send SIGALRM to a `disco.py` PID from your desktop notification manager:
![image](https://user-images.githubusercontent.com/18216480/134602925-efa51f1c-f17a-4db4-9409-2f20381492ae.png)

**Comment by smgd** [comment]
cool!
